version: '3'
services:
  redis:
    image: redis
    container_name: my-redis
    ports:
      - '127.0.0.1:6379:6379/tcp'
  redisinsight:
    image: redislabs/redisinsight
    container_name: redisinsight
    ports:
      - '127.0.0.1:5540:5540'
    depends_on:
      - redis
