openapi: 3.0.0
info:
  title: E-commerce API
  description: API endpoints for a e-commerce services documented on swagger.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1/e-commerce
    description: Local server
paths:
  /user/register:
    post:
      tags:
        - User Controller
      summary: Register
      parameters:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
          description: API key for authorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  example: johndoe@mail.com
      responses:
        '204':
          description: No Content
        '409':
          description: Conflict
        '404':
          description: Not Found
        '500':
          description: Server Error
  /user/verify-email:
    get:
      tags:
        - User Controller
      summary: Verification account via email
      parameters:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
          description: API key for authorization
        - name: token
          in: query
          required: true
          schema:
            type: string
          description: API key for authorization
      responses:
        '201':
          description: Created
        '409':
          description: Conflict
        '404':
          description: Not Found
        '500':
          description: Server Error
  /template/create:
    post:
      tags:
        - Template Controller
      summary: Create a template
      parameters:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
          description: API key for authorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  example: 'HTML_EMAIL_SEND_TOKEN'
      responses:
        '201':
          description: Created
        '409':
          description: Conflict
        '404':
          description: Not Found
        '500':
          description: Server Error
# components:
#   securitySchemes:
#     ApiKeyAuth:
#       type: apiKey
#       in: header
#       name: x-api-key
