openapi: 3.0.0
info:
  title: E-commerce API
  description: API endpoints for a e-commerce services documented on swagger.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1/e-commerce
    description: Local server
paths:
  /APIKey:
    $ref: './paths/apiKey.yaml'
  /APIKey/{id}:
    $ref: './paths/apiKeyID.yaml'
  /user/register:
    post:
      tags:
        - User Controller
      summary: Register
      security:
        - x-api-key: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  example: johndoe@mail.com
      responses:
        '204':
          description: No Content
        '409':
          description: Conflict
        '404':
          description: Not Found
        '500':
          description: Server Error
  /user/verify-email:
    get:
      tags:
        - User Controller
      summary: Verification account via email
      security:
        - x-api-key: []
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
          description: API key for authorization
      responses:
        '201':
          description: Created
        '404':
          description: Not Found
        '500':
          description: Server Error
  /user/login:
    post:
      tags:
        - User Controller
      summary: User login with email and password
      security:
        - x-api-key: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: 'example@gmail.com'
                password:
                  type: string
      responses:
        '201':
          description: Created
        '404':
          description: Not Found
        '500':
          description: Server Error
  /user/logout:
    delete:
      tags:
        - User Controller
      summary: User login with email and password
      security:
        - bearerAuth: []
        - apiKey: []
        - clientID: []
      responses:
        '200':
          description: Created
        '404':
          description: Not Found
        '500':
          description: Server Error
  /template/:
    $ref: './paths/templateMail.yaml'
  /template/{id}:
    $ref: './paths/templateMailID.yaml'
components:
  securitySchemes:
    $ref: './schemas/securitySchemes.yaml'
