openapi: 3.0.0
info:
  title: E-commerce API
  description: API endpoints for a e-commerce services documented on swagger.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api/v1/e-commerce'
    description: Local server
paths:
  /APIKey:
    post:
      tags:
        - API Key Controller
      summary: Create a new API key
      security:
        - x-api-key: []
        - x-client-id: []
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - permissions
              properties:
                permissions:
                  type: array
                  example:
                    - '2222'
                    - '3333'
      responses:
        '201':
          description: Created
        '404':
          description: Not Found
        '500':
          description: Server Error
    get:
      tags:
        - API Key Controller
      summary: Get list API keys
      security:
        - x-api-key: []
        - x-client-id: []
        - bearerAuth: []
      responses:
        '200':
          description: Ok
        '404':
          description: Not Found
        '500':
          description: Server Error
  '/APIKey/{id}':
    delete:
      tags:
        - API Key Controller
      summary: Delete a API key
      security:
        - x-api-key: []
        - x-client-id: []
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: id
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Server Error
  /user/register:
    post:
      tags:
        - User Controller
      summary: Register
      security:
        - x-api-key: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  example: johndoe@mail.com
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
        '409':
          description: Conflict
        '500':
          description: Server Error
  /user/verify-email:
    get:
      tags:
        - User Controller
      summary: Verification account via email
      security:
        - x-api-key: []
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
          description: API key for authorization
      responses:
        '201':
          description: Created
        '404':
          description: Not Found
        '500':
          description: Server Error
  /user/login:
    post:
      tags:
        - User Controller
      summary: User login with email and password
      security:
        - x-api-key: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: example@gmail.com
                password:
                  type: string
      responses:
        '201':
          description: Created
        '404':
          description: Not Found
        '500':
          description: Server Error
  /user/logout:
    delete:
      tags:
        - User Controller
      summary: User login with email and password
      security:
        - bearerAuth: []
        - apiKey: []
        - clientID: []
      responses:
        '200':
          description: Created
        '404':
          description: Not Found
        '500':
          description: Server Error
  /template/:
    post:
      tags:
        - Template Controller
      summary: Create a template
      security:
        - x-api-key: []
        - x-client-id: []
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  example: HTML_EMAIL_SEND_TOKEN
      responses:
        '201':
          description: Created
        '404':
          description: Not Found
        '409':
          description: Conflict
        '500':
          description: Server Error
    get:
      tags:
        - Template Controller
      summary: Get list templates
      security:
        - x-api-key: []
        - x-client-id: []
        - bearerAuth: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Server Error
  '/template/{id}':
    delete:
      tags:
        - Template Controller
      summary: delete a template
      security:
        - x-api-key: []
        - x-client-id: []
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: id
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Server Error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    apiKey:
      type: apiKey
      in: header
      name: x-api-key
    clientID:
      type: apiKey
      in: header
      name: x-client-id
